# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MungGu iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MungGu iOS
  pod 'NVActivityIndicatorView'

  target 'MungGu iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MungGu iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
